name: CI

on: [push]

jobs:
  dummy-test:
    name: ansible syntax-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test dummy action
        run: |
          ansible-playbook -i localhost, site.yml --syntax-check
